// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvb.proto

package peer // import "github.com/hyperledger/fabric/protos/peer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KvbMessageType int32

const (
	KvbMessage_VALID   KvbMessageType = 0
	KvbMessage_INVALID KvbMessageType = 1
)

var KvbMessageType_name = map[int32]string{
	0: "VALID",
	1: "INVALID",
}
var KvbMessageType_value = map[string]int32{
	"VALID":   0,
	"INVALID": 1,
}

func (x KvbMessageType) Enum() *KvbMessageType {
	p := new(KvbMessageType)
	*p = x
	return p
}
func (x KvbMessageType) String() string {
	return proto.EnumName(KvbMessageType_name, int32(x))
}
func (x *KvbMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(KvbMessageType_value, data, "KvbMessageType")
	if err != nil {
		return err
	}
	*x = KvbMessageType(value)
	return nil
}
func (KvbMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kvb_504bce46be14c565, []int{0, 0}
}

type KvbMessage struct {
	State                *KvbMessageType `protobuf:"varint,1,opt,name=state,enum=protos.KvbMessageType" json:"state,omitempty"`
	Key                  *string         `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value                *string         `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *KvbMessage) Reset()         { *m = KvbMessage{} }
func (m *KvbMessage) String() string { return proto.CompactTextString(m) }
func (*KvbMessage) ProtoMessage()    {}
func (*KvbMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_kvb_504bce46be14c565, []int{0}
}
func (m *KvbMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvbMessage.Unmarshal(m, b)
}
func (m *KvbMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvbMessage.Marshal(b, m, deterministic)
}
func (dst *KvbMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvbMessage.Merge(dst, src)
}
func (m *KvbMessage) XXX_Size() int {
	return xxx_messageInfo_KvbMessage.Size(m)
}
func (m *KvbMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KvbMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KvbMessage proto.InternalMessageInfo

func (m *KvbMessage) GetState() KvbMessageType {
	if m != nil && m.State != nil {
		return *m.State
	}
	return KvbMessage_VALID
}

func (m *KvbMessage) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KvbMessage) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*KvbMessage)(nil), "protos.KvbMessage")
	proto.RegisterEnum("protos.KvbMessageType", KvbMessageType_name, KvbMessageType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessClient is the client API for Access service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessClient interface {
	GetState(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error)
	PutState(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error)
	WriteBlock(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error)
}

type accessClient struct {
	cc *grpc.ClientConn
}

func NewAccessClient(cc *grpc.ClientConn) AccessClient {
	return &accessClient{cc}
}

func (c *accessClient) GetState(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error) {
	out := new(KvbMessage)
	err := c.cc.Invoke(ctx, "/protos.Access/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessClient) PutState(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error) {
	out := new(KvbMessage)
	err := c.cc.Invoke(ctx, "/protos.Access/PutState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessClient) WriteBlock(ctx context.Context, in *KvbMessage, opts ...grpc.CallOption) (*KvbMessage, error) {
	out := new(KvbMessage)
	err := c.cc.Invoke(ctx, "/protos.Access/WriteBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServer is the server API for Access service.
type AccessServer interface {
	GetState(context.Context, *KvbMessage) (*KvbMessage, error)
	PutState(context.Context, *KvbMessage) (*KvbMessage, error)
	WriteBlock(context.Context, *KvbMessage) (*KvbMessage, error)
}

func RegisterAccessServer(s *grpc.Server, srv AccessServer) {
	s.RegisterService(&_Access_serviceDesc, srv)
}

func _Access_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvbMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Access/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServer).GetState(ctx, req.(*KvbMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Access_PutState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvbMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServer).PutState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Access/PutState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServer).PutState(ctx, req.(*KvbMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Access_WriteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvbMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServer).WriteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Access/WriteBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServer).WriteBlock(ctx, req.(*KvbMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Access_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Access",
	HandlerType: (*AccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _Access_GetState_Handler,
		},
		{
			MethodName: "PutState",
			Handler:    _Access_PutState_Handler,
		},
		{
			MethodName: "WriteBlock",
			Handler:    _Access_WriteBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvb.proto",
}

func init() { proto.RegisterFile("kvb.proto", fileDescriptor_kvb_504bce46be14c565) }

var fileDescriptor_kvb_504bce46be14c565 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2e, 0x4b, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xcd, 0x8c, 0x5c, 0x5c, 0xde,
	0x65, 0x49, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0xba, 0x5c, 0xac, 0xc5, 0x25, 0x89,
	0x25, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xe2, 0x10, 0xd5, 0xc5, 0x7a, 0x08, 0x25,
	0x7a, 0x25, 0x95, 0x05, 0xa9, 0x41, 0x10, 0x55, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69,
	0xaa, 0x04, 0x33, 0x58, 0x0c, 0xc2, 0x51, 0x92, 0xe3, 0x62, 0x01, 0x69, 0x13, 0xe2, 0xe4, 0x62,
	0x0d, 0x73, 0xf4, 0xf1, 0x74, 0x11, 0x60, 0x10, 0xe2, 0xe6, 0x62, 0xf7, 0xf4, 0x83, 0x70, 0x18,
	0x8d, 0xd6, 0x30, 0x72, 0xb1, 0x39, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x0b, 0x99, 0x70, 0x71, 0xb8,
	0xa7, 0x96, 0x04, 0x83, 0x8d, 0x17, 0xc2, 0xb4, 0x5e, 0x0a, 0x8b, 0x98, 0x12, 0x03, 0x48, 0x57,
	0x40, 0x29, 0xc9, 0xba, 0xcc, 0xb8, 0xb8, 0xc2, 0x8b, 0x32, 0x4b, 0x52, 0x9d, 0x72, 0xf2, 0x93,
	0xb3, 0x89, 0xd7, 0xe7, 0xa4, 0x1d, 0xa5, 0x99, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c,
	0x9f, 0xab, 0x9f, 0x51, 0x59, 0x90, 0x5a, 0x94, 0x93, 0x9a, 0x92, 0x9e, 0x5a, 0xa4, 0x9f, 0x96,
	0x98, 0x54, 0x94, 0x99, 0xac, 0x0f, 0xd1, 0xa4, 0x5f, 0x90, 0x9a, 0x5a, 0x04, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x63, 0xe5, 0xf0, 0xd7, 0x75, 0x01, 0x00, 0x00,
}
